In [19]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import joblib
import warnings 
warnings.filterwarnings("ignore")

In [2]:
dataset = pd.read_csv("finance.csv")
dataset.head()

,transaction_id,customer_age,account_balance,transaction_amount,merchant_rating,credit_score,loan_amount,monthly_income,num_of_dependents,emi_amount,...,device_type,payment_mode,city,employment_type,loan_status,card_type,customer_segment,transaction_type,fraud_flag,target
0,1,56,328741.15,28543.38,2.8,395,338636.34,21525.11,5,42510.34,...,Tablet,Card,Delhi,Business,Approved,Gold,High,Offline,1,0
1,2,69,229911.81,2396.58,3.6,852,953144.05,75560.27,0,42696.69,...,Mobile,UPI,Nashik,Business,Approved,Silver,Low,Offline,0,0
2,3,46,136674.67,81390.53,4.2,855,875865.14,186823.33,1,14985.46,...,Laptop,Card,Nagpur,Salaried,Rejected,Platinum,High,Online,0,0
3,4,32,347078.85,77187.20,4.7,539,71270.02,153102.00,3,3292.47,...,Tablet,Wallet,Pune,Self-Employed,Rejected,Gold,High,Online,0,0
4,5,60,334438.19,87107.83,4.1,490,57372.41,72899.39,1,47930.60,...,Laptop,Card,Delhi,Self-Employed,Rejected,Platinum,Medium,Offline,0,0

In [3]:
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [4]:
x.head()

,transaction_id,customer_age,account_balance,transaction_amount,merchant_rating,credit_score,loan_amount,monthly_income,num_of_dependents,emi_amount,...,risk_score,device_type,payment_mode,city,employment_type,loan_status,card_type,customer_segment,transaction_type,fraud_flag
0,1,56,328741.15,28543.38,2.8,395,338636.34,21525.11,5,42510.34,...,0.309,Tablet,Card,Delhi,Business,Approved,Gold,High,Offline,1
1,2,69,229911.81,2396.58,3.6,852,953144.05,75560.27,0,42696.69,...,0.750,Mobile,UPI,Nashik,Business,Approved,Silver,Low,Offline,0
2,3,46,136674.67,81390.53,4.2,855,875865.14,186823.33,1,14985.46,...,0.002,Laptop,Card,Nagpur,Salaried,Rejected,Platinum,High,Online,0
3,4,32,347078.85,77187.20,4.7,539,71270.02,153102.00,3,3292.47,...,0.448,Tablet,Wallet,Pune,Self-Employed,Rejected,Gold,High,Online,0
4,5,60,334438.19,87107.83,4.1,490,57372.41,72899.39,1,47930.60,...,0.816,Laptop,Card,Delhi,Self-Employed,Rejected,Platinum,Medium,Offline,0

In [5]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [6]:
numeric_feature = x.select_dtypes(exclude=["object"]).columns
catag_feature = x.select_dtypes(include=["object"]).columns

In [7]:
numeric_feature

Index(['transaction_id', 'customer_age', 'account_balance',
       'transaction_amount', 'merchant_rating', 'credit_score', 'loan_amount',
       'monthly_income', 'num_of_dependents', 'emi_amount', 'years_with_bank',
       'savings_amount', 'insurance_amount', 'investment_score', 'risk_score',
       'fraud_flag'],
      dtype='object')

In [8]:
catag_feature

Index(['device_type', 'payment_mode', 'city', 'employment_type', 'loan_status',
       'card_type', 'customer_segment', 'transaction_type'],
      dtype='object')

In [9]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [12]:
catag_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=False))
])

In [13]:
preprocess_pipeline = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_feature),
    ("catag", catag_pipeline, catag_feature)
])

In [14]:
clean = preprocess_pipeline.fit(x)

In [15]:
Clean_data = pd.DataFrame(clean.transform(x))

In [16]:
Clean_data.head()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,-1.732029,0.606848,0.546070,-0.749163,-0.177108,-1.176207,-0.568218,-1.640671,1.464414,1.199983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-1.731986,1.396837,-0.140539,-1.654514,0.514906,1.464470,1.569496,-0.842861,-1.463609,1.213147,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,-1.731943,-0.000836,-0.788296,1.080705,1.033917,1.481805,1.300663,0.799898,-0.878004,-0.744430,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
3,-1.731899,-0.851593,0.673470,0.935161,1.466426,-0.344134,-1.498317,0.302015,0.293205,-1.570446,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
4,-1.731856,0.849922,0.585650,1.278670,0.947415,-0.627270,-1.546663,-0.882148,-0.878004,1.582881,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0

In [17]:
joblib.dump(clean, "knn_preprocess_pipeline.pkl")

['knn_preprocess_pipeline.pkl']

In [18]:
joblib.load("knn_preprocess_pipeline.pkl")

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['transaction_id', 'customer_age', 'account_balance',
       'transaction_amount', 'merchant_rating', 'credit_score', 'loan_amount',
       'monthly_income', 'num_of_dependents', 'emi_amount', 'years_with_bank',
       'savings_amount', 'insur...risk_score',
       'fraud_flag'],
      dtype='object')),
                                ('catag',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['device_type', 'payment_mode', 'city', 'employment_type', 'loan_status',
       'card_type', 'customer_segment', 'transaction_type'],
      dtype='object'))])

In [23]:
x_train, x_test, y_train, y_test = train_test_split(
    Clean_data, y, test_size=0.2, random_state=42
)

In [24]:
model = KNeighborsClassifier(
    n_neighbors=7,
    weights='distance',
    metric='minkowski',
    p=2
)

In [25]:
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7, weights='distance')

In [29]:
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

In [30]:
print("Training Accuracy:", accuracy_score(y_train, y_train_pred))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred))

Training Accuracy: 1.0
Testing Accuracy: 0.845

In [31]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

Confusion Matrix:
[[13488   145]
 [ 2335    32]]

In [32]:
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.99      0.92     13633
           1       0.18      0.01      0.03      2367

    accuracy                           0.84     16000
   macro avg       0.52      0.50      0.47     16000
weighted avg       0.75      0.84      0.78     16000

In [33]:
joblib.dump(model, "knn.pkl")

['knn.pkl']